#!/usr/bin/env python3
"""Generate the verified runner/bundle pair used by the curl installer."""
from __future__ import annotations

import argparse
import re
import subprocess
from pathlib import Path

RUNNER_ROOT = Path(__file__).resolve().parents[1]
LOCK_PATH = RUNNER_ROOT / "installer-compatibility.lock"


def run_git(repo: Path, *args: str) -> str:
    result = subprocess.run(
        ["git", "-C", str(repo), *args],
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode:
        message = result.stderr.strip() or result.stdout.strip()
        raise RuntimeError(f"git {' '.join(args)} failed in {repo}: {message}")
    return result.stdout.strip()


def resolve_release(repo: Path, ref: str) -> str:
    if not re.fullmatch(r"v[0-9][0-9A-Za-z._-]*", ref):
        raise ValueError(f"installer refs must be version tags, got {ref!r}")
    return run_git(repo, "rev-parse", "--verify", f"{ref}^{{commit}}")


def render_lock(
    *,
    runner_ref: str,
    runner_commit: str,
    bundle_ref: str,
    bundle_commit: str,
) -> str:
    return (
        "# Generated by scripts/update_installer_compatibility.py; "
        "do not edit by hand.\n"
        "schema=coursecraft.runner_compatibility/1\n"
        f"runner_ref={runner_ref}\n"
        f"runner_commit={runner_commit}\n"
        f"bundle_ref={bundle_ref}\n"
        f"bundle_commit={bundle_commit}\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--runner-ref", required=True, help="Published runner tag")
    parser.add_argument("--bundle-ref", required=True, help="Published bundle tag")
    parser.add_argument(
        "--bundle-dir",
        type=Path,
        default=RUNNER_ROOT.parent / "brightspace-blueprint-bundle",
        help="Path to the companion bundle repository",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=LOCK_PATH,
        help="Compatibility record to write",
    )
    args = parser.parse_args()

    bundle_repo = args.bundle_dir.expanduser().resolve()
    runner_commit = resolve_release(RUNNER_ROOT, args.runner_ref)
    bundle_commit = resolve_release(bundle_repo, args.bundle_ref)
    payload = render_lock(
        runner_ref=args.runner_ref,
        runner_commit=runner_commit,
        bundle_ref=args.bundle_ref,
        bundle_commit=bundle_commit,
    )
    output = args.output.expanduser().resolve()
    output.write_text(payload, encoding="utf-8")
    print(f"wrote {output}")
    print(f"  runner {args.runner_ref} {runner_commit}")
    print(f"  bundle {args.bundle_ref} {bundle_commit}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
